### ISSUE TITLE
D/S ratio

### ISSUE THREAD

**Issue by mtinnes** [melexis/mlx90632-library#16]
Maybe the wrong place for this, but we are developing a thermal sensing application for reading body temperature using the MLX90632. I can't find any information on the distance to spot ratio for this sensor. We are trying to determine how far from the sensor we can get and still obtain accurate reading of say the forehead area.

**Comment by LBuydens** [comment]
Dear sir,
This is indeed not the right place for this non-software related question.  Our application engineers are not monitoring github.  
Please contact your distributor or sales@melexis.com.
