### ISSUE TITLE
tearDown setUp functions

### ISSUE THREAD

**Issue by sison54** [melexis/mlx90632-library#20]
Are the mock_mlx90632_depends.h and mock_mlx90632_depends.c files available? I dont see them in the repository.

Thanks

**Comment by Letme** [comment]
They are generated by CMock at build time.

**Comment by Letme** [comment]
If you install rake and run `make utest` it should use Ceedling  (CMock and Unity) to generate all the needed things for unit testing (and run), which will produce all the mock files.

**Comment by michig54** [comment]
I get linker errors that the setUp and tearDown functions are missing from the test files. It works fine once I add them (or rename SetUp to setUp).

**Comment by Letme** [comment]
Did you install Ceedling from gem, or you run the one which is referenced here with submodules? 

But him, I do see inconsistency among `Test*` files, so you can open a pull request with aligning all that to small `setUp`, if that is the only error.

**Comment by sison54** [comment]
I am using the one referenced in the submodule. I will create a pull request to fix this.

**Comment by sison54** [comment]
Added pull request #21

**Comment by Letme** [comment]
Merged. Thanks for reporting and fixing.
