### ISSUE TITLE
EE_VERSION fails on MLX90632_XTD_RNG_KEY at mlx90632_init

### ISSUE THREAD

**Issue by KammutierSpule** [melexis/mlx90632-library#32]
Hello,
I'm using a extended device.

It returns an error on mlx90632_init
```
if ((eeprom_version & 0x7F00) == MLX90632_XTD_RNG_KEY)
    {
        return ERANGE;
    }
```

What does it mean?

**Comment by Letme** [comment]
https://github.com/melexis/mlx90632-library/blob/master/inc/mlx90632.h#L366

**Comment by KammutierSpule** [comment]
thanks I understand now :)
