### ISSUE TITLE
Extended range measurement 

### ISSUE THREAD

**Issue by MarsHo1970** [melexis/mlx90632-library#39]
Merry Christmas!
    Which chip does the extended mode apply to?
    My chiptype is "MLX90632SLDBCB-000RE",
    I found that the extended mode measurement is incorrect.
    Can you help me？

**Comment by Letme** [comment]
Can you read registers? Then you can check in code which version your chip was calibrated to.

**Comment by MarsHo1970** [comment]
Thank you for your help
The contents of the register I read are shown in the picture.
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



Access | Address | Name | Description | Readout
-- | -- | -- | -- | --
Read-only | 0x2405 | ID0[15:0] | Chipversion | 0X5018
Read-only | 0x2406 | ID1[15:0] | Chipversion | 0XE6E5
Read-only | 0x2407 | ID2[15:0] | Chipversion | 0XE584
Read-only | 0x2408 | ID_CRC16 | CRC | 0X0000
Read-only | 0x2409 | EE_PRODUCT_CODE | Sensorinformation | 0X0000
Read-only | 0x240B | EE_VERSION | EEPROMversion | 0X0205



</body>

</html>

**Comment by MarsHo1970** [comment]
Is there anything unusual?

**Comment by Letme** [comment]
A quick check at source code you might as well see if you get ERANGE value from the `mlx90632_init` function (https://github.com/melexis/mlx90632-library/blob/master/src/mlx90632.c#L467-L469). I am currently only looking at online stuff so define-resolution of address/value supported is up to you.

**Comment by MarsHo1970** [comment]
Thank you for your help！
