### ISSUE TITLE
EEPROM version register documentation mismatch with library ?

### ISSUE THREAD

**Issue by linkineo** [melexis/mlx90632-library#46]
We're using both Medical/Extended-grade and standard versions of the sensor. 

In the library during initialization, the following check is performed in the EEPROM version register **0x240b**
https://github.com/melexis/mlx90632-library/blob/0b1be08be1191f7244b3b65eac74a1614edaf3b8/src/mlx90632.c#L467

with 
https://github.com/melexis/mlx90632-library/blob/0b1be08be1191f7244b3b65eac74a1614edaf3b8/inc/mlx90632.h#L192

Yet the latest datasheet from your [website](https://www.melexis.com/en/documents/documentation/datasheets/datasheet-mlx90632) does not document this register. It however documents the product code like this: 

<img width="1123" alt="image" src="https://github.com/melexis/mlx90632-library/assets/7335332/ef030c2e-17b3-4dc1-9533-74811a726df3">

Questions:
Is the magic 0x0500 always reflecting a medical-grade device or which meaning does it have ? Why not use in the library the product code as a way to identify a medical-grade device ?

**Comment by Letme** [comment]
`0x0500` does not mention anything about medical-grade device, so I am not sure why you would think this is connected?

The extended range is read at initialization (https://github.com/melexis/mlx90632-library/blob/0b1be08be1191f7244b3b65eac74a1614edaf3b8/src/mlx90632.c#L446) from `EE_VERSION` (https://github.com/melexis/mlx90632-library/blob/master/inc/mlx90632.h#L87) which is on address `0x240B` and it defines the eeprom content variation which enables us to keep some backwards compatibility with older versions as well as with newer extended range versions. The product code you are referencing is not present in older devices.

**Comment by Letme** [comment]
I am cleaning up the open issues and this seems to be resolved.
