### ISSUE TITLE
Issue with MLX90632 accuracy and performance

### ISSUE THREAD

**Issue by AjaxCDL** [melexis/mlx90632-library#48]
We are evaluating MLX90632 for use in a vitals monitor

It is observed that the surface temperature given out by MLX90632 is off by 3 degrees from the actual.
Also, it is observed that when the sensor is pointed at the hand or chest of a person, it takes about 17 minutes to get a stable surface temperature.   

Does anyone have an observation how to correct this and get the correct surface temperature in a short time (such as 500ms or 1 sec)?

**Comment by Letme** [comment]
Can you tell a bit more about your test setup? Is surface temperature uniformly covering the sensor's field of view? Did you include the emissivity of your surface or are you using black body?

**Comment by Letme** [comment]
Just as a side comment - there is nothing in the sensor that would "even temperature out" over time in minutes. Even with slowest refresh rate set.

**Comment by AjaxCDL** [comment]
> Can you tell a bit more about your test setup? Is surface temperature uniformly covering the sensor's field of view? Did you include the emissivity of your surface or are you using black body?

@Letme We have used the emissivity of 1 for our calculations. The measurements were taken from an actual body surface and not black body. Even using an emissivity of 0.98 for human body does not alter the results much. The surface temperature uniformly covers the sensor's field of view as it is kept at 7mm distance from the sensor

**Comment by AjaxCDL** [comment]
> Can you tell a bit more about your test setup? Is surface temperature uniformly covering the sensor's field of view? Did you include the emissivity of your surface or are you using black body?

Our application is such that the sensor is closer to the shoulder where there is no hair

**Comment by AjaxCDL** [comment]
> Just as a side comment - there is nothing in the sensor that would "even temperature out" over time in minutes. Even with slowest refresh rate set.

We are using the sensor in the continuous mode with readings taken at every 500ms and we see that the temperature readings gradually increase over a period of 15 to 17 minutes and the final stable reading is off by about 3 degrees F from the surface temperature

**Comment by Letme** [comment]
The actual body surface is a bad constant temperature surface. It changes with your heart rate, with "local weather" (wind gusts, sweat), etc. How do you know the real temperature of the surface - by some contact sensor?

And how do you know it is 3 degrees F off? That is 16 degrees Celsius and that is what I would say is the difference between room temperature of skin on the hand vs body core temperature, just by bluntly pointing the sensor to my hand when I am not sick and I had hands in the air for some time (without making a fist, etc).

**Comment by karelv** [comment]
Hello Ajax,

MLX90632 measures surface temperature. In the case of human core body, it is often skin temperature that is measured.
This is not the same as core body temperature, it depends on the location where the temperature is measured and other factors like ambient temperature, airflow, sweating, etc...

We can assist you further, please contact our sales team
https://melexis.com/mlx90632

Best regards,
Karel.

**Comment by Letme** [comment]
The last proposal from Karel should be a default point of contact for people that want to have some more information about body core temperature calculations. The current driver will not include that, because what we have is not medically verified, so we do not want to cause any confussion.
