### ISSUE TITLE
Remove requirement to define BITS_PER_LONG

### ISSUE THREAD

**Issue by Letme** [melexis/mlx90632-library#52]
After changes by @adnan-ashraf in https://github.com/melexis/mlx90632-library/pull/50#issuecomment-2276514619 the BITS_PER_LONG definition is no longer a requirement, but we did not clean it from documentation, nor did we remove the warning from the `inc/mlx90632.h` when it is not defined.

To clarify: there was no issue with the previous GENMASK (taken from Linux kernel), but this change was accepted because it did not require BITS_PER_LONG setting anymore.

**Comment by adnan-ashraf** [comment]
> To clarify: there was no issue with the previous GENMASK (taken from Linux kernel), but this change was accepted because it did not require BITS_PER_LONG setting anymore.

The problem was that the GENMASK definition was not generating the desired mask on 64-bit Windows, as mentioned in [#50 (comment)](https://github.com/melexis/mlx90632-library/pull/50#issuecomment-2276141920).
