### ISSUE TITLE
Can't clone git repository recursively

### ISSUE THREAD

**Issue by giova23** [melexis/mlx90632-library#9]
mlx90632 library gets cloned OK, but  ceedling tries to use ssh and fails:

root@vst:~# git clone --recursive https://github.com/melexis/mlx90632-library.git
Cloning into 'mlx90632-library'...
remote: Counting objects: 274, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 274 (delta 16), reused 24 (delta 15), pack-reused 246
Receiving objects: 100% (274/274), 281.45 KiB | 197.00 KiB/s, done.
Resolving deltas: 100% (109/109), done.
Checking connectivity... done.
Submodule 'tools/ceedling' (git@github.com:ThrowTheSwitch/Ceedling.git) registered for path 'tools/ceedling'
Cloning into 'tools/ceedling'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
**Permission denied (publickey).
fatal: Could not read from remote repository.**

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ThrowTheSwitch/Ceedling.git' into submodule path 'tools/ceedling' failed

**Comment by Letme** [comment]
Thanks for reporting. I have changed ceedling submodule to https, but I would still recommend you to add ssh-key to your github account.
